# Generated by Django 2.2.4 on 2019-08-02 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='title',
            new_name='answer_text',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='title',
            new_name='question_text',
        ),
    ]
