# Generated by Django 2.2.4 on 2019-08-02 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exams', '0002_auto_20190802_1024'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsweredQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-created_at'], 'verbose_name': 'Respuesta', 'verbose_name_plural': 'Respuestas'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_at'], 'verbose_name': 'Pregunta', 'verbose_name_plural': 'Preguntas'},
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('active', models.BooleanField(default=True, verbose_name='activo')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nombre')),
                ('last_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Apellidos')),
                ('birthdate', models.DateField(verbose_name='Fecha de nacimiento')),
                ('contact', models.DateField(verbose_name='Télefono de contacto')),
                ('civil_status', models.CharField(choices=[('SO', 'Solter@'), ('CA', 'Casad@'), ('DI', 'Divorciad@'), ('VI', 'Viud@')], default='SO', max_length=2, verbose_name='Estado civil')),
                ('live_accompanied', models.BooleanField(default=True, verbose_name='¿Vive acompañado?')),
                ('disease', models.BooleanField(default=True, verbose_name='¿Sufre de alguna enfermedad?')),
                ('drugs', models.TextField(verbose_name='¿Qué medicamentos toma?')),
                ('answered_questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.AnsweredQuestion', verbose_name='Respuesta de pregunta')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='answeredquestion',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='exams.Answer', verbose_name='Pregunta'),
        ),
        migrations.AddField(
            model_name='answeredquestion',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='exams.Question', verbose_name='Pregunta'),
        ),
    ]
