# Generated by Django 2.2.4 on 2019-08-02 16:23

import autoslug.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_auto_20190802_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=django.utils.timezone.now, editable=False, populate_from='question_text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='slug',
            field=autoslug.fields.AutoSlugField(default=django.utils.timezone.now, editable=False, populate_from='question_text'),
            preserve_default=False,
        ),
    ]
