# Generated by Django 2.2.4 on 2019-08-02 16:26

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_auto_20190802_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Respuesta'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='answer_text'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Pregunta'),
        ),
    ]
