# Generated by Django 2.2.4 on 2019-08-02 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_auto_20190802_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Contacto'),
        ),
    ]
