# Generated by Django 2.2.4 on 2019-08-02 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_auto_20190802_1137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-created_at'], 'verbose_name': 'Exámen', 'verbose_name_plural': 'Exámenes'},
        ),
        migrations.AddField(
            model_name='answeredquestion',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='exams.Exam', verbose_name='Examen'),
        ),
        migrations.AlterField(
            model_name='answeredquestion',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='exams.Answer', verbose_name='Respuesta'),
        ),
        migrations.RemoveField(
            model_name='exam',
            name='answered_questions',
        ),
        migrations.AddField(
            model_name='exam',
            name='answered_questions',
            field=models.ManyToManyField(through='exams.AnsweredQuestion', to='exams.Question', verbose_name='Respuesta de pregunta'),
        ),
    ]
