# Generated by Django 2.2.4 on 2019-08-02 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0010_auto_20190802_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='recommendation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.Recommendation', verbose_name='Recomendación'),
        ),
    ]
