# Generated by Django 2.2.4 on 2019-08-02 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0011_exam_recommendation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='bottom',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='lower',
            field=models.IntegerField(default=0, verbose_name='Puntaje inferior'),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='upper',
            field=models.IntegerField(default=100, verbose_name='Puntaje superior'),
        ),
    ]
